INSERT INTO BEVERAGE (ID, NAME, COST, BEVERAGE_SIZE) VALUES (1, 'americano', 1000, 0);
INSERT INTO BEVERAGE (ID, NAME, COST, BEVERAGE_SIZE) VALUES (2, 'coldbrew', 1500, 0);
INSERT INTO BEVERAGE (ID, NAME, COST, BEVERAGE_SIZE) VALUES (3, 'latte', 2000, 0);

INSERT INTO CUSTOMER (ID, NAME) VALUES (1, 'customer1');
INSERT INTO CUSTOMER (ID, NAME) VALUES (2, 'customer2');
INSERT INTO CUSTOMER (ID, NAME) VALUES (3, 'customer3');

INSERT INTO "order" (ID, MILEAGE_POINT, PAYMENT, STATUS, TOTAL_COST, CUSTOMER_ID) VALUES (100, 100, 1, 1, 3000, 1);
INSERT INTO ORDER_ITEM (ID, COUNT, BEVERAGE_ID, ORDER_ID) VALUES (1, 3, 1, 100);
